version: "3.7"
services:
  localstack:
    container_name: jt-pubsub
    image: localstack/localstack:latest
    hostname: localstack
    ports:
      - "4566-4568:4566-4568"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
  